[wazuh_server]
wazuh-server ansible_host=192.168.56.10 ansible_connection=local

[agent_node]
agent-node ansible_host=192.168.56.20 ansible_connection=local

[attacker]
attacker ansible_host=192.168.56.30 ansible_connection=local

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_user=vagrant
