---
# roles/wazuh_agent/handlers/main.yml

- name: Restart wazuh-agent
  ansible.builtin.systemd:
    name: wazuh-agent
    state: restarted
  listen: "Restart wazuh-agent"

- name: Restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
  listen: "Restart rsyslog"
